export const TRANSLATION_IDS=['BSB','ESV','NIV','NLT','CSB','NKJV','MSG','AMP','CEV','NASB2020','eng_kjv','eng_asv','ENGWEBP','eng_dby','eng_ylt','eng_dra']
export const DEFAULT_PREFERENCES={translation:'BSB',enabled:TRANSLATION_IDS,favorites:['BSB'],order:TRANSLATION_IDS,compare:['eng_kjv','eng_asv','ENGWEBP'],parallel:true,fontSize:21,lineHeight:1.65,libraryView:'grid',librarySort:'title',libraryDirection:'asc',confession:'1689',guideAudience:'personal',guideLength:'standard',commentary:'matthew-henry'}
const choices=(value,allowed,fallback)=>allowed.includes(value)?value:fallback
const ids=value=>Array.isArray(value)?[...new Set(value.filter(v=>TRANSLATION_IDS.includes(v)))]:[]
export function normalizePreferences(value={}){
 const v=value&&typeof value==='object'?value:{};const translation=choices(v.translation,TRANSLATION_IDS,'BSB');
 const enabled=ids(v.enabled??TRANSLATION_IDS);if(!enabled.includes(translation))enabled.unshift(translation)
 const order=ids(v.order??TRANSLATION_IDS);TRANSLATION_IDS.forEach(id=>{if(!order.includes(id))order.push(id)})
 return {translation,enabled,order,favorites:ids(v.favorites??['BSB']).filter(id=>enabled.includes(id)),compare:ids(v.compare??DEFAULT_PREFERENCES.compare).filter(id=>enabled.includes(id)&&id!==translation),parallel:typeof v.parallel==='boolean'?v.parallel:true,fontSize:choices(Number(v.fontSize),[18,21,24,28],21),lineHeight:choices(Number(v.lineHeight),[1.45,1.65,1.9],1.65),libraryView:choices(v.libraryView,['grid','list','shelf'],'grid'),librarySort:choices(v.librarySort,['title','author','category','recent'],'title'),libraryDirection:choices(v.libraryDirection,['asc','desc'],'asc'),confession:choices(v.confession,['1689','abstract1858','dort1619','nh1833','chicago1978','nicene','danvers1987'],'1689'),guideAudience:choices(v.guideAudience,['personal','small-group','teaching'],'personal'),guideLength:choices(v.guideLength,['concise','standard','detailed'],'standard'),commentary:choices(v.commentary,['matthew-henry','john-calvin','john-gill','adam-clarke','jamieson-fausset-brown','keil-delitzsch','tyndale'],'matthew-henry')}
}
export const preferencesFor=user=>normalizePreferences(user?.user_metadata?.bsd_preferences)
export function orderedTranslations(catalog,prefs){return prefs.order.filter(id=>prefs.enabled.includes(id)).sort((a,b)=>Number(prefs.favorites.includes(b))-Number(prefs.favorites.includes(a))).map(id=>catalog.find(t=>t.id===id)).filter(Boolean)}
export function parseSettingsFile(text){const file=JSON.parse(text);if(file?.format!=='bsd-settings'||file.version!==1||!file.preferences||typeof file.preferences!=='object'||Array.isArray(file.preferences))throw new Error('Choose a BSD settings export (version 1).');return normalizePreferences(file.preferences)}
