export const SERMON_SOURCES={youtube:'YouTube',podcast:'Podcast',audio:'Audio link',video:'Video link',text:'Text / Transcript',other:'Other'}
export function sourceType(url){try{const u=new URL(url);if(/(^|\.)(youtube\.com|youtu\.be)$/.test(u.hostname))return 'youtube';if(/\.(mp3|m4a|ogg|wav)$/i.test(u.pathname))return 'audio';if(/\.(mp4|webm|mov)$/i.test(u.pathname))return 'video';return /podcast|spotify|apple\.com/.test(u.hostname)?'podcast':'other'}catch{return 'text'}}
export function sermonTitle(s){if(s.title?.trim())return s.title;try{return new URL(s.source_url).hostname}catch{return s.speaker?`${s.speaker} — ${s.sermon_date||'Sermon'}`:'Untitled sermon'}}
export function timestamp(seconds){const n=Math.floor(seconds);return `${Math.floor(n/3600)?Math.floor(n/3600)+':':''}${String(Math.floor(n/60)%60).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function seconds(value){const pieces=value.replace(',','.').split(':').map(Number);return pieces.reduce((n,v)=>n*60+v,0)}
export function parseTimedTranscript(input){
 const cues=[];const blocks=input.replace(/^\uFEFF/,'').replace(/\r/g,'').split(/\n\s*\n/)
 for(const block of blocks){const lines=block.split('\n'),i=lines.findIndex(l=>l.includes('-->'));if(i<0)continue;const m=lines[i].match(/((?:\d{2,}:)?\d{2}:\d{2}[.,]\d{3})\s*-->\s*((?:\d{2,}:)?\d{2}:\d{2}[.,]\d{3})/);if(!m)throw new Error('A transcript timestamp could not be read. Check the SRT/VTT file.');const start=seconds(m[1]),end=seconds(m[2]);const text=lines.slice(i+1).join('\n').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>');if(end<start)throw new Error('A timestamp ends before it starts.');if(text.trim())cues.push({start,end,text})}
 if(!cues.length)throw new Error('No timed transcript cues were found.');return {text:cues.map(c=>c.text).join('\n\n'),cues:cues.sort((a,b)=>a.start-b.start)}
}
export function uniqueSermonRefs(refs){return [...new Map(refs.filter(r=>r.chapter>0&&(!r.verseStart||r.verseStart>0)&&(!r.verseEnd||r.verseEnd>=r.verseStart)).map(r=>[`${r.book}:${r.chapter}:${r.verseStart||''}:${r.verseEnd||''}`,{book:r.book,chapter:r.chapter,verseStart:r.verseStart||null,verseEnd:r.verseEnd||null,raw:`${r.book} ${r.chapter}${r.verseStart?':'+r.verseStart+(r.verseEnd>r.verseStart?'-'+r.verseEnd:''):''}`}])).values()]}
export function sermonPassageMatch(s,ref){return [...(s.primary_ref?[s.primary_ref]:[]),...(s.detected_refs||[])].some(r=>r.book===ref.book&&r.chapter===ref.chapter&&(!ref.verseStart||!r.verseStart||(r.verseStart<=(ref.verseEnd||ref.verseStart)&&(r.verseEnd||r.verseStart)>=ref.verseStart)))}
export function guideText(s){const g=s.study_guide;if(!g)return s.notes||'';return [g.summary,'Outline',...(g.outline||[]),'Key Points',...(g.key_points||[]),'Discussion Questions',...(g.discussion_questions||[]),'Application',...(g.application||[]),'Cross-References',...(g.cross_refs||[]).map(r=>`${r.ref}: ${r.note}`)].join('\n\n')}
export function filterSermons(rows,{query='',source='',speaker='',series='',tag='',church='',from='',to='',added='',transcript='',favorite=false}={}){const words=query.toLowerCase().trim().split(/\s+/);return rows.filter(s=>(!source||s.source_type===source)&&(!speaker||s.speaker===speaker)&&(!series||s.series===series)&&(!church||s.church===church)&&(!tag||s.tags?.includes(tag))&&(!favorite||s.favorite)&&(!added||s.created_at?.slice(0,10)>=added)&&(!from||s.sermon_date>=from)&&(!to||s.sermon_date&&s.sermon_date<=to)&&(!transcript||(transcript==='yes')===!!s.transcript_text?.trim())&&words.every(w=>[s.title,s.primary_text,s.speaker,s.series,s.church,s.description,s.notes,...s.tags||[],...(s.detected_refs||[]).map(r=>r.raw)].join(' ').toLowerCase().includes(w)))}

export function sermonBibleUrl(ref,id){const p=new URLSearchParams({book:ref.book,chapter:String(ref.chapter),sermon:id});if(ref.verseStart)p.set('verse',ref.verseStart);if(ref.verseEnd)p.set('verseEnd',ref.verseEnd);return '/bible?'+p}
