import AccountLink from '../components/AccountLink'
import { useEffect, useRef, useState } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../App'
import { listEntries, createEntry, deleteEntry, formatEntryNum, getLinksFor, setRelated } from '../lib/entries'
import { loadCheckLibrary } from '../lib/checkLibrary'
import { checksList } from '../lib/theologyCheck'
import { NOTE_TYPES, noteType, exportNote } from '../lib/noteModel'
import NoteWorkspaceEditor from '../components/NoteWorkspaceEditor'
import './Notes.css'
import { saveTopicLink } from '../lib/topics'
import NoteMenu from '../components/NoteMenu'
import { BookOpen, FileText, ShieldCheck, NotebookPen, Library, Search, ChevronDown, UserRound } from 'lucide-react'
const TYPE_ICONS={scripture:BookOpen,book:Library,doctrine_check:ShieldCheck,bible_study:NotebookPen,resource:FileText,standalone:FileText}
export default function NotesWorkspace() {
  const user=useAuth(), {id}=useParams(), navigate=useNavigate(), location=useLocation()
  const [notes,setNotes]=useState(null),[books,setBooks]=useState([]),[checks,setChecks]=useState([]),[error,setError]=useState(''),[contextError,setContextError]=useState(''),[pendingDelete,setPendingDelete]=useState(null),[deleting,setDeleting]=useState(false)
  const [query,setQuery]=useState(''),[type,setType]=useState(''),[tag,setTag]=useState(''),[sort,setSort]=useState('updated'),[creating,setCreating]=useState(false),[view,setView]=useState('workspace'),[source,setSource]=useState('')
  const saveRef=useRef(null),deleteDialog=useRef(null)
  useEffect(()=>{if(pendingDelete)deleteDialog.current?.showModal();else deleteDialog.current?.close()},[pendingDelete])
  const [desktop,setDesktop]=useState(()=>window.matchMedia('(min-width:761px)').matches)
  useEffect(()=>{const media=window.matchMedia('(min-width:761px)');const change=()=>setDesktop(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[])
  const isNew=location.pathname==='/notebook/new'
  async function load(){setError('');try{setNotes(await listEntries(user.id))}catch(err){setError(err.message)}}
  useEffect(()=>{load();Promise.allSettled([loadCheckLibrary(user.id),checksList()]).then(([b,c])=>{if(b.status==='fulfilled')setBooks(b.value);if(c.status==='fulfilled')setChecks(c.value.data||[]);if(b.status==='rejected'||c.status==='rejected')setContextError('Some linked names could not be loaded. Existing links are preserved.')})},[user.id])
  async function open(next,details=false) {try{await saveRef.current?.flush();if(next)setView('workspace');navigate(next?`/notebook/${next}${details?'?details=1':''}`:'/notebook',{state:next?null:{listOnly:true}})}catch{setError('The current note has unsaved changes. Retry saving before switching notes.')}}
  async function makeNote(source) {
    if(creating)return
    setCreating(true);setError('')
    try {
      await saveRef.current?.flush()
      const prefill=source?.id&&source.id===saveRef.current?.snapshot().id?{...saveRef.current.snapshot(),title:source.title}:source || (isNew?location.state:null) || {}
      const row=await createEntry(user.id,{title:prefill.title||'Untitled note',body:prefill.body||'',rich_doc:prefill.rich_doc||null,ref:prefill.ref||null,tags:prefill.tags||[],note_type:prefill.note_type || (prefill.shelf_book_id?'book':prefill.doctrine_check_id?'doctrine_check':prefill.ref?'scripture':'standalone'),shelf_book_id:prefill.shelf_book_id||null,doctrine_check_id:prefill.doctrine_check_id||null,resource_title:prefill.resource_title||null,resource_url:prefill.resource_url||null,photos:prefill.photos||[],page:prefill.page||null,video_url:prefill.video_url||null,stance:prefill.stance||null,sermon_id:prefill.sermon_id||null})
      if(source?.id){try{const links=await getLinksFor(source.id);if(links.seeAlso.length)await setRelated(row.id,links.seeAlso.map(n=>n.id))}catch{setError('The note was copied, but its manual note links could not be copied. You can add them in Advanced tools.')}}
      if(prefill.topic_key){try{await saveTopicLink(user.id,prefill.topic_key,'note',row.id,row.title)}catch{setError('Note saved. The topic link could not be saved; its topic tag is retained.')}}
      setView('workspace');setNotes(current=>[...(current||[]).filter(n=>n.id!==row.id),row]);navigate(`/notebook/${row.id}`,{replace:isNew})
    }catch(err){setError(err.message)}finally{setCreating(false)}
  }
  function remove(note){setPendingDelete(note)}
  async function confirmRemove() {
    if(deleting||!pendingDelete)return
    const note=pendingDelete;setDeleting(true)
    try{await saveRef.current?.flush();await deleteEntry(note.id);localStorage.removeItem(`bsd-note-draft:${user.id}:${note.id}`);setNotes(current=>current.filter(n=>n.id!==note.id));if(id===note.id)navigate('/notebook',{state:{listOnly:true}});setPendingDelete(null)}catch(err){setError(err.message)}finally{setDeleting(false)}
  }
  const selected=notes?.find(n=>n.id===id) || (!id&&!isNew&&desktop&&view==='workspace'&&!location.state?.listOnly?notes?.slice().sort((a,b)=>Date.parse(b.updated_at||b.created_at)-Date.parse(a.updated_at||a.created_at))[0]:null)
  const tags=[...new Set((notes||[]).flatMap(n=>n.tags||[]))].sort()
  const filtered=(notes||[]).filter(n=>{
    const book=books.find(b=>b.id===n.shelf_book_id),check=checks.find(c=>c.id===n.doctrine_check_id)
    return (!new URLSearchParams(location.search).get('doctrine') || n.doctrine_check_id===new URLSearchParams(location.search).get('doctrine')) && (!type||noteType(n)===type)&&(!source||n.shelf_book_id===source||n.doctrine_check_id===source||n.resource_url===source)&&(!tag||n.tags?.includes(tag))&&(!query.trim()||[n.title,n.body,n.ref,...(n.tags||[]),book?.title,book?.author,check?.title,check?.name,n.resource_title].join(' ').toLowerCase().includes(query.trim().toLowerCase()))
  }).sort((a,b)=>sort==='title'?(a.title||'').localeCompare(b.title||''):new Date(sort==='created'?b.created_at:b.updated_at||b.created_at)-new Date(sort==='created'?a.created_at:a.updated_at||a.created_at))
  return <div className={`page notes-workspace ${selected||isNew?'has-selection':''} notes-view-${view}`}><div className="notes-topbar"><label className="notes-global-search"><Search size={19}/><input aria-label="Search all notes" placeholder="Search notes, titles, tags, references…" value={query} onChange={e=>setQuery(e.target.value)}/></label><AccountLink user={user}/><blockquote>“Let the word of Christ dwell in you richly…”<cite>Colossians 3:16</cite></blockquote></div>{contextError&&<p role="status">{contextError}</p>}{error&&<p role="alert">{error} <button onClick={load}>Reload notes</button></p>}
    <div className="notes-layout"><aside className="notes-browser"><header><div><h1>My Notes</h1><p>Capture. Connect. Grow.</p></div><div className="notes-new-split"><button className="btn btn-primary" disabled={creating||notes===null} onClick={()=>makeNote()}>{creating?'Creating…':'+ New Note'}</button><NoteMenu label="Choose new note type" actions={Object.entries(NOTE_TYPES).map(([value,label])=>({label:`New ${label} note`,run:()=>makeNote({note_type:value})}))}><ChevronDown size={16}/></NoteMenu></div></header>
    <button className="btn btn-ghost" onClick={async()=>{try{await saveRef.current?.flush();navigate('/notebook/trash')}catch{setError('Save the current note before opening Trash.')}}}>Trash — recover deleted notes</button><div className="notes-view-switch" aria-label="Notes view">{['workspace','list','grid'].map(value=><button key={value} aria-pressed={view===value} onClick={async()=>{try{await saveRef.current?.flush();setView(value);navigate('/notebook',{state:{listOnly:value!=='workspace'}})}catch{setError('Save the current note before changing views.')}}}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div>
    <input className="input" aria-label="Search notes" placeholder="Search notes, titles, tags, references…" value={query} onChange={e=>setQuery(e.target.value)}/><nav className="notes-type-tabs" aria-label="Filter by note type">{[['','All Notes'],...Object.entries(NOTE_TYPES)].map(([value,label])=><button key={value} aria-pressed={type===value} onClick={()=>setType(value)}>{label} ({(notes||[]).filter(n=>!value||noteType(n)===value).length})</button>)}</nav><div className="notes-list-filters"><select aria-label="Sort notes" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">Recently Updated</option><option value="created">Recently Created</option><option value="title">Title</option></select><select aria-label="Filter notes by tag" value={tag} onChange={e=>setTag(e.target.value)}><option value="">All tags</option>{tags.map(t=><option key={t}>{t}</option>)}</select></div><select className="notes-source-filter" aria-label="Filter by linked source" value={source} onChange={e=>setSource(e.target.value)}><option value="">All linked sources</option>{books.filter(b=>notes?.some(n=>n.shelf_book_id===b.id)).map(b=><option value={b.id} key={b.id}>{b.title}</option>)}{checks.filter(c=>notes?.some(n=>n.doctrine_check_id===c.id)).map(c=><option key={c.id} value={c.id}>{c.title||c.name}</option>)}{[...new Set((notes||[]).map(n=>n.resource_url).filter(Boolean))].map(url=><option value={url} key={url}>{notes.find(n=>n.resource_url===url)?.resource_title||url}</option>)}</select>
    {notes===null?<div role="status" className="notes-skeleton">Loading notes…</div>:!notes.length?<div className="notes-empty"><h2>Your study notes will appear here.</h2><p>Capture observations from Scripture, books, Doctrine Check, and your study.</p></div>:!filtered.length?<div className="notes-empty"><h2>No notes match this search.</h2><button onClick={()=>{setQuery('');setType('');setTag('');setSource('');if(location.search)navigate('/notebook')}}>Clear search and filters</button></div>:<div className="notes-list">{filtered.map(n=><article className={n.id===selected?.id?'selected':''} key={n.id}><button className="notes-row-open" onClick={()=>open(n.id)}><span className="notes-type-icon">{(()=>{const Icon=TYPE_ICONS[noteType(n)]||FileText;return <Icon size={20} aria-hidden="true"/>})()}</span><strong>{n.title||'Untitled'}</strong><span>{n.ref||books.find(b=>b.id===n.shelf_book_id)?.title||n.resource_title||NOTE_TYPES[noteType(n)]}</span><div className="notes-row-tags"><span>{NOTE_TYPES[noteType(n)]}</span>{(n.tags||[]).filter(t=>t.toLowerCase()!==NOTE_TYPES[noteType(n)]?.toLowerCase()).slice(0,2).map(t=><span key={t}>{t}</span>)}</div>{view==='grid'&&<p className="notes-excerpt">{n.body?.slice(0,150)}</p>}<small>no. {formatEntryNum(n.number)} · {new Date(n.updated_at||n.created_at).toLocaleDateString()}</small></button><div className="notes-row-menu"><NoteMenu label={`Actions for ${n.title||'Untitled'}`} actions={[
      {label:'Open',run:()=>open(n.id)},
      ...['Change Note Type','Manage Tags','Link Scripture / Book / Doctrine / Resource'].map(label=>({label,run:()=>open(n.id,true)})),
      {label:'Export as Markdown',run:()=>exportNote(saveRef.current?.snapshot().id===n.id?saveRef.current.snapshot():n)},
      {label:'Duplicate',run:()=>makeNote({...n,title:`${n.title||'Untitled'} (copy)`})},
      {label:'Move to Trash',danger:true,run:()=>remove(n)}
    ]}/></div></article>)}</div>}</aside>
    {isNew?<section className="notes-editor card"><h2>New study note</h2><p>{location.state?.ref?`Linked Scripture: ${location.state.ref}`:'Choose a note type, then create your note.'}</p><button className="btn btn-primary" disabled={creating||notes===null} onClick={()=>makeNote()}>Create note</button></section>:selected?<NoteWorkspaceEditor key={selected.id} note={selected} notes={notes} userId={user.id} books={books} checks={checks} saveRef={saveRef} onSaved={row=>setNotes(current=>current.map(n=>n.id===row.id?row:n))} onOpen={open} onDuplicate={n=>makeNote({...n,title:`${n.title||'Untitled'} (copy)`})} onDelete={remove}/>:<section className="notes-editor notes-empty card"><h2>{notes===null?'Loading your study desk…':id?'Note unavailable':'Your study desk'}</h2><p>{id?'This note could not be found in your account.':'Select a note to read, edit, and explore its connections.'}</p><button className="notes-back btn btn-secondary" onClick={()=>open(null)}>Back to Notes</button></section>}
    </div><dialog ref={deleteDialog} className="notes-confirm-dialog" aria-labelledby="notes-delete-title" onCancel={()=>!deleting&&setPendingDelete(null)}><h2 id="notes-delete-title">Move note to Trash?</h2><p>Move “{pendingDelete?.title||'Untitled'}” to Trash? You can restore it later.</p><div><button autoFocus disabled={deleting} onClick={()=>setPendingDelete(null)}>Cancel</button><button className="notes-delete" disabled={deleting} onClick={confirmRemove}>{deleting?'Moving…':'Move to Trash'}</button></div></dialog></div>
}
