import {useEffect,useRef,useState} from 'react'
import {Link,useNavigate,useParams} from 'react-router-dom'
import {useAuth} from '../App'
import {supabase} from '../lib/supabase'
import {createEntry,formatEntryNum} from '../lib/entries'
import {getSermon,updateSermon,transcriptFields,deleteSermon,downloadTranscript,generateStudyGuide} from '../lib/sermons'
import {sermonTitle,SERMON_SOURCES,guideText} from '../lib/sermonModel'
import {safeNoteUrl} from '../lib/noteModel'
import {SermonRefs,SermonTranscript,GuideBody} from '../components/SermonStudy'
import {loadTopicData,saveTopicLink} from '../lib/topics'
import {topicCatalog} from '../lib/topicCatalog'
import './Sermons.css'
export default function SermonDetail(){const {id}=useParams(),user=useAuth(),navigate=useNavigate();const [row,setRow]=useState(null),[notes,setNotes]=useState([]),[allNotes,setAllNotes]=useState([]),[topics,setTopics]=useState([]),[tab,setTab]=useState('Overview'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[guideDraft,setGuideDraft]=useState(null),[topicId,setTopicId]=useState(''),[noteId,setNoteId]=useState('');const visited=useRef(null);useEffect(()=>{let active=true;getSermon(user.id,id).then(data=>{if(active){setRow(data);setError('')}}).catch(e=>{if(active)setError(e.message)});supabase.from('entries').select('id,title,number,sermon_id').eq('user_id',user.id).then(({data,error})=>{if(active){if(error)setError('Related notes could not load.');else{setAllNotes(data||[]);setNotes((data||[]).filter(n=>n.sermon_id===id))}}});loadTopicData(user.id).then(d=>{if(active)setTopics(topicCatalog(d.personal,d.notes,d.books,d.checks,d.sermons||[]))});if(visited.current!==id){visited.current=id;supabase.rpc('record_sermon_view',{p_sermon_id:id}).then(({error})=>{if(error&&active)setError('Viewing history could not be saved.')})}return()=>{active=false}},[id,user.id,retry]);
 async function action(fn){if(busy)return;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function patch(values){setRow(await updateSermon(user.id,id,values))}
 async function exportGuide(){const existing=notes.find(n=>n.id===row.notebook_entry_id);if(existing){navigate(`/notebook/${existing.id}`);return}const note=await createEntry(user.id,{title:`Study Guide: ${sermonTitle(row)}`,body:guideText(row),tags:['sermon',...row.tags],sermon_id:id,note_type:'resource',resource_title:sermonTitle(row),resource_url:row.source_url});setNotes(ns=>[...ns,note]);try{await patch({notebook_entry_id:note.id})}catch{setError('Your note was created, but the study-guide shortcut could not be saved. Find it under Notes.');return}navigate(`/notebook/${note.id}`)}
 async function linkNote(){const {error}=await supabase.from('entries').update({sermon_id:id}).eq('user_id',user.id).eq('id',noteId);if(error)throw error;setNotes(ns=>[...ns,allNotes.find(n=>n.id===noteId)]);setNoteId('')}
 function downloadText(){const url=URL.createObjectURL(new Blob([row.transcript_text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=sermonTitle(row).replace(/[^a-z0-9 -]/gi,'').slice(0,80)+'.txt';a.click();URL.revokeObjectURL(url)}
 if(!row||row.id!==id)return <div className="page">{error?<p role="alert">{error} <button onClick={()=>setRetry(r=>r+1)}>Retry</button></p>:<p>Loading sermon…</p>}<Link to="/sermons">All Sermons</Link></div>
 return <div className="page sermons-page"><header><div><Link to="/sermons">← All Sermons</Link><h1>{sermonTitle(row)}</h1><p>{[row.speaker,row.series,row.sermon_date].filter(Boolean).join(' · ')}</p></div><div className="sermon-actions"><button className="btn btn-secondary" disabled={busy} onClick={()=>action(()=>patch({favorite:!row.favorite}))}>{row.favorite?'★ Favorite':'☆ Favorite'}</button><Link className="btn btn-secondary" to={`/sermons/${id}/edit`}>Edit</Link><button className="btn" disabled={busy} onClick={()=>{if(confirm('Delete this sermon and its uploaded transcript? Your linked notes will remain.'))action(async()=>{await deleteSermon(user.id,row);navigate('/sermons')})}}>Delete</button></div></header>{error&&<p role="alert">{error} <button onClick={()=>setRetry(r=>r+1)}>Retry loading</button></p>}<div className="sermon-detail-layout"><aside className="card sermon-metadata"><div className="sermon-feature"><strong>{sermonTitle(row)}</strong><span>{row.speaker}</span></div><dl>{[['Source',SERMON_SOURCES[row.source_type]],['Series',row.series||'Stand-alone'],['Church',row.church||'—'],['Date preached',row.sermon_date||'—'],['Added',new Date(row.created_at).toLocaleDateString()]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{safeNoteUrl(row.source_url)&&<a className="btn btn-primary" href={row.source_url} target="_blank" rel="noreferrer">Open original source ↗</a>}{row.transcript_text&&<button className="btn btn-secondary" onClick={downloadText}>Download transcript text</button>}{row.transcript_path&&<button className="btn" disabled={busy} onClick={()=>action(()=>downloadTranscript(row.transcript_path))}>Download original file</button>}<Link className="btn" to="/notebook/new" state={{sermon_id:id,title:`Notes: ${sermonTitle(row)}`,tags:row.tags,note_type:'resource',resource_title:sermonTitle(row),resource_url:row.source_url}}>Create linked note</Link></aside><section className="card sermon-detail-main"><nav className="sermon-tabs">{['Overview','Transcript','Scripture','Study Guide','Notes'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}{t==='Scripture'?` (${row.detected_refs.length})`:t==='Notes'?` (${notes.length})`:''}</button>)}</nav>
 {tab==='Overview'&&<><h2>About This Sermon</h2><p>{row.description||'Add a description from Edit.'}</p><h3>Topics</h3><div className="sermon-chips">{row.tags.map(t=><Link key={t} to={`/topics?tag=${encodeURIComponent(t)}`}>{t}</Link>)}</div><label>Link to a topic<select className="input" value={topicId} onChange={e=>setTopicId(e.target.value)}><option value="">Choose topic…</option>{topics.map(t=><option key={t.key} value={t.key}>{t.name}</option>)}</select></label><button className="btn" disabled={!topicId||busy} onClick={()=>action(async()=>{const t=topics.find(t=>t.key===topicId);await saveTopicLink(user.id,topicId,'sermon',id,sermonTitle(row));await patch({tags:[...new Set([...row.tags,t.name])]});setTopicId('')})}>Link Topic</button><h3>Personal Notes</h3><p className="sermon-text">{row.notes||'No personal notes yet.'}</p><h3>Detected Scripture</h3><SermonRefs sermon={row}/></>}
 {tab==='Transcript'&&<><div className="sermon-actions"><Link to={`/sermons/${id}/edit`}>Edit transcript</Link><button disabled={busy} onClick={()=>action(()=>patch(transcriptFields(row.transcript_text,row.transcript_cues)))}>Re-detect references</button></div><SermonTranscript sermon={row}/></>}
 {tab==='Scripture'&&<><h2>Scripture References</h2><p>Explicit references detected in the transcript. Open a passage to keep this sermon alongside Bible Study.</p><SermonRefs sermon={row}/></>}
 {tab==='Study Guide'&&<><div className="sermon-actions"><button className="btn btn-primary" disabled={busy||!row.transcript_text.trim()} onClick={()=>{if(!row.study_guide||confirm('Regenerate this study guide? This replaces the saved guide and uses the AI service.'))action(async()=>{await generateStudyGuide(id);setRow(await getSermon(user.id,id));setGuideDraft(null)})}}>{busy?'Working…':row.study_guide?'Regenerate':'Generate Study Guide'}</button>{row.study_guide&&<><button className="btn" disabled={busy} onClick={()=>setGuideDraft(structuredClone(row.study_guide))}>Edit Guide</button><button className="btn btn-secondary" disabled={busy} onClick={()=>action(exportGuide)}>{row.notebook_entry_id?'Open saved guide note':'Export to Notes'}</button></>}</div><p className="card-meta">AI-assisted; compare the guide with the sermon and Scripture. Generation runs only when requested.</p>{row.study_guide_generated_at&&<small>Generated {new Date(row.study_guide_generated_at).toLocaleString()}{row.transcript_imported_at>row.study_guide_generated_at?' · Transcript has changed since generation.':''}</small>}{guideDraft?<form onSubmit={e=>{e.preventDefault();action(async()=>{await patch({study_guide:guideDraft});setGuideDraft(null)})}}><label>Summary<textarea className="input" value={guideDraft.summary} onChange={e=>setGuideDraft(g=>({...g,summary:e.target.value}))}/></label>{['outline','key_points','discussion_questions','application'].map(k=><label key={k}>{k.replaceAll('_',' ')} — one item per line<textarea className="input" rows={5} value={(guideDraft[k]||[]).join('\n')} onChange={e=>setGuideDraft(g=>({...g,[k]:e.target.value.split('\n')}))}/></label>)}{guideDraft.cross_refs.map((r,i)=><fieldset key={i}><label>Reference<input className="input" value={r.ref} onChange={e=>setGuideDraft(g=>({...g,cross_refs:g.cross_refs.map((v,j)=>j===i?{...v,ref:e.target.value}:v)}))}/></label><label>Explanation<input className="input" value={r.note} onChange={e=>setGuideDraft(g=>({...g,cross_refs:g.cross_refs.map((v,j)=>j===i?{...v,note:e.target.value}:v)}))}/></label></fieldset>)}<button className="btn btn-primary" disabled={busy}>Save Guide</button><button type="button" className="btn" onClick={()=>setGuideDraft(null)}>Cancel</button></form>:row.study_guide?<GuideBody guide={row.study_guide}/>:<p>{row.transcript_text?'Generate an outline, theological points, discussion questions, application prompts, and cross-references.':'Add a transcript before generating a study guide.'}</p>}</>}
 {tab==='Notes'&&<><h2>Linked Notes</h2>{notes.map(n=><div className="sermon-note-row" key={n.id}><Link to={`/notebook/${n.id}`}>No. {formatEntryNum(n.number)} · {n.title||'Untitled'}</Link><button disabled={busy} onClick={()=>action(async()=>{const {error}=await supabase.from('entries').update({sermon_id:null}).eq('id',n.id).eq('user_id',user.id);if(error)throw error;setNotes(ns=>ns.filter(x=>x.id!==n.id));if(row.notebook_entry_id===n.id)await patch({notebook_entry_id:null})})}>Unlink</button></div>)}{!notes.length&&<p>No linked notes yet.</p>}<label>Link an existing note<select className="input" value={noteId} onChange={e=>setNoteId(e.target.value)}><option value="">Choose note…</option>{allNotes.filter(n=>!n.sermon_id&&!notes.some(x=>x.id===n.id)).map(n=><option key={n.id} value={n.id}>{n.title||'Untitled'}</option>)}</select></label><button className="btn" disabled={!noteId||busy} onClick={()=>action(linkNote)}>Link Note</button><Link className="btn btn-primary" to="/notebook/new" state={{sermon_id:id,title:`Notes: ${sermonTitle(row)}`,tags:row.tags,note_type:'resource'}}>New Sermon Note</Link></>}
 </section></div></div>
}
