import {useEffect,useState} from 'react'
import {Link,useNavigate,useParams} from 'react-router-dom'
import {useAuth} from '../App'
import {getSermon,saveSermon,transcriptFields,uploadTranscript,removeTranscript} from '../lib/sermons'
import {readTranscript} from '../lib/sermonImports'
import {SERMON_SOURCES,sourceType} from '../lib/sermonModel'
import {safeNoteUrl} from '../lib/noteModel'
import './Sermons.css'
const EMPTY={title:'',speaker:'',series:'',church:'',sermon_date:'',source_url:'',source_type:'text',tags:[],notes:'',description:'',image_url:'',transcript_text:'',transcript_cues:[]}
export default function SermonComposer(){const user=useAuth(),navigate=useNavigate(),{id}=useParams();const [form,setForm]=useState(EMPTY),[original,setOriginal]=useState(null),[file,setFile]=useState(null),[loading,setLoading]=useState(!!id),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tagText,setTagText]=useState('');useEffect(()=>{let active=true;if(id)getSermon(user.id,id).then(row=>{if(active){setOriginal(row);setForm({...EMPTY,...row});setTagText(row.tags.join(', '));setLoading(false)}}).catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false}},[id,user.id]);const change=(key,value)=>setForm(f=>({...f,[key]:value}));
 async function importFile(next){if(!next)return;setBusy(true);setError('');try{const parsed=await readTranscript(next);setFile(next);setForm(f=>({...f,transcript_text:parsed.text,transcript_cues:parsed.cues}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function save(e){e.preventDefault();setBusy(true);setError('');let uploaded=null;const sermonId=id||crypto.randomUUID();try{if(form.source_url&&!safeNoteUrl(form.source_url))throw new Error('Use a valid http or https source URL.');if(form.image_url&&!safeNoteUrl(form.image_url))throw new Error('Use a valid http or https image URL.');if(form.transcript_text.length>1000000)throw new Error('Transcript exceeds one million characters.');if(file)uploaded=await uploadTranscript(user.id,sermonId,file);const values=Object.fromEntries(['title','speaker','series','church','source_type','notes','description'].map(k=>[k,form[k]?.trim()||'']));Object.assign(values,{sermon_date:form.sermon_date||null,source_url:form.source_url||null,image_url:form.image_url||null,tags:[...new Set(tagText.split(',').map(t=>t.trim()).filter(Boolean))],...(!original||form.transcript_text!==original.transcript_text||JSON.stringify(form.transcript_cues)!==JSON.stringify(original.transcript_cues)?transcriptFields(form.transcript_text,form.transcript_cues):{}),...(uploaded?{transcript_path:uploaded,transcript_filename:file.name}:{})});await saveSermon(user.id,sermonId,values);if(uploaded&&original?.transcript_path){try{await removeTranscript(original.transcript_path)}catch{console.warn('Previous transcript upload could not be removed.')}}navigate(`/sermons/${sermonId}`)}catch(e){if(uploaded)try{await removeTranscript(uploaded)}catch{}setError(e.message)}finally{setBusy(false)}}
 if(loading)return <div className="page">Loading sermon…</div>;if(id&&!original)return <div className="page"><p role="alert">{error||'Sermon unavailable'}</p><Link to="/sermons">Back to Sermons</Link></div>
 return <div className="page sermons-page"><header><div><h1>{id?'Edit Sermon':'New Sermon'}</h1><p>Listen. Read. Study. Apply.</p></div><Link to={id?`/sermons/${id}`:'/sermons'}>Cancel</Link></header><form className="card sermon-form" onSubmit={save}><div className="sermon-form-grid">{[['title','Title'],['speaker','Speaker'],['series','Series'],['church','Church'],['sermon_date','Date preached']].map(([key,label])=><label key={key}>{label}<input className="input" type={key==='sermon_date'?'date':'text'} value={form[key]||''} onChange={e=>change(key,e.target.value)}/></label>)}<label>Source URL<input className="input" type="url" value={form.source_url||''} onChange={e=>setForm(f=>({...f,source_url:e.target.value,source_type:sourceType(e.target.value)}))}/></label><label>Source type<select className="input" value={form.source_type} onChange={e=>change('source_type',e.target.value)}>{Object.entries(SERMON_SOURCES).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Tags / Topics<input className="input" value={tagText} onChange={e=>setTagText(e.target.value)} placeholder="Separate tags with commas"/></label><label>Optional image URL<input className="input" type="url" value={form.image_url||''} onChange={e=>change('image_url',e.target.value)}/></label></div><label>Description<textarea className="input" rows={3} value={form.description} onChange={e=>change('description',e.target.value)}/></label><section className="sermon-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)importFile(e.dataTransfer.files[0])}}><label>Upload transcript — TXT, PDF, DOCX, SRT or VTT (up to 20 MB)<input disabled={busy} type="file" accept=".txt,.pdf,.docx,.srt,.vtt" onChange={e=>importFile(e.target.files[0])}/></label><p>{file?`Selected: ${file.name}`:original?.transcript_filename||'Drop a file here or choose a file.'}</p></section><label>Transcript text<textarea className="input" rows={16} value={form.transcript_text} onChange={e=>setForm(f=>({...f,transcript_text:e.target.value,transcript_cues:[]}))}/></label>{form.transcript_cues.length>0&&<p>{form.transcript_cues.length} timestamps imported. Editing the text manually removes timing alignment.</p>}<label>Personal notes<textarea className="input" rows={4} value={form.notes} onChange={e=>change('notes',e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="btn btn-primary" disabled={busy}>{busy?'Processing…':'Save Sermon'}</button></form></div>
}
