import AccountLink from '../components/AccountLink'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { Search, SlidersHorizontal, Star, BookOpen, FileText, Library, ShieldCheck, Mic } from 'lucide-react'
import { useAuth } from '../App'
import NoteMenu from '../components/NoteMenu'
import TopicDialog from '../components/TopicDialog'
import { TOPIC_CATEGORIES, TOPIC_GROUPS, topicCatalog, topicContent, matchesTopic, normalizeTopic } from '../lib/topicCatalog'
import { loadTopicData, saveTopic, saveTopicLink, setTopicPreference, recordTopicView, deletePersonalTopic, unlinkTopic } from '../lib/topics'
import { parseReference } from '../lib/bsb'
import { safeNoteUrl } from '../lib/noteModel'
import './Topics.css'
const EMPTY={personal:[],links:[],preferences:[],notes:[],books:[],checks:[],sermons:[],errors:[]}
const SOURCES=['My Topics','Built-in Topics','From My Notes','From My Library','From Doctrine Check','From Sermons']
const TYPES=[['scripture','Scripture'],['book','Books'],['note','Notes'],['resource','Resources'],['doctrine_check','Doctrine Check'],['sermon','Sermons']]
const split=value=>[...new Set(value.split(',').map(t=>t.trim()).filter(Boolean))]
const route=key=>`/topics/${encodeURIComponent(key)}`
function bibleUrl(value){const p=parseReference(value.replace(/[–—]/g,'-'));return p?`/bible?book=${encodeURIComponent(p.book)}&chapter=${p.chapter}${p.verseStart?`&verse=${p.verseStart}&verseEnd=${p.verseEnd||p.verseStart}`:''}`:null}
function relative(value){if(!value)return 'Not viewed yet';const hours=Math.max(0,Math.floor((Date.now()-Date.parse(value))/3600000));return hours<1?'Viewed just now':hours<24?`Viewed ${hours} hours ago`:`Viewed ${Math.floor(hours/24)} days ago`}

export default function TopicWorkspace(){
  const user=useAuth(),navigate=useNavigate(),{topicKey}=useParams(),[params,setParams]=useSearchParams()
  const [data,setData]=useState(EMPTY),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState(null),[busy,setBusy]=useState(false)
  const [draftQuery,setDraftQuery]=useState(params.get('q')||params.get('tag')||''),[query,setQuery]=useState(params.get('q')||params.get('tag')||''),[localQuery,setLocalQuery]=useState('')
  const [now]=useState(()=>Date.now())
  const [tab,setTab]=useState('All Topics'),[categories,setCategories]=useState([]),[sources,setSources]=useState([]),[tags,setTags]=useState([]),[related,setRelated]=useState([]),[sort,setSort]=useState('az'),[view,setView]=useState('grid'),[limit,setLimit]=useState(24),[collection,setCollection]=useState(''),[favorites,setFavorites]=useState(false),[dateAdded,setDateAdded]=useState(''),[filterOpen,setFilterOpen]=useState(false)
  const filterDialog=useRef(null),visited=useRef(null)
  const reload=useCallback(async()=>{setLoading(true);try{setData(await loadTopicData(user.id));setError('')}catch(e){setError(e.message)}finally{setLoading(false)}},[user.id])
  useEffect(()=>{reload()},[reload])
  useEffect(()=>{if(filterOpen)filterDialog.current?.showModal();else filterDialog.current?.close()},[filterOpen])
  const catalog=useMemo(()=>topicCatalog(data.personal,data.notes,data.books,data.checks,data.sermons),[data])
  const contents=useMemo(()=>Object.fromEntries(catalog.map(t=>[t.key,topicContent(t,data,data.links)])),[catalog,data])
  const prefs=Object.fromEntries(data.preferences.map(p=>[p.topic_key,p]))
  const selected=catalog.find(t=>t.key===topicKey)
  useEffect(()=>{if(!selected){if(!topicKey)visited.current=null;return}if(visited.current===selected.key)return;visited.current=selected.key;recordTopicView(selected.key).then(()=>setData(d=>{const old=d.preferences.find(p=>p.topic_key===selected.key)||{};return {...d,preferences:[...d.preferences.filter(p=>p.topic_key!==selected.key),{...old,topic_key:selected.key,view_count:(old.view_count||0)+1,last_viewed:new Date().toISOString()}]}})).catch(()=>setError('The topic is available, but viewing history could not be saved.'))},[selected,topicKey])
  async function preference(topic,values,propagate=false){if(busy)return;setBusy(true);try{const row=await setTopicPreference(user.id,topic.key,values);setData(d=>({...d,preferences:[...d.preferences.filter(p=>p.topic_key!==topic.key),row]}))}catch(e){setError(e.message);if(propagate)throw e}finally{setBusy(false)}}
  function actions(topic){return [{label:'Open Topic',run:()=>navigate(route(topic.key))},{label:prefs[topic.key]?.favorite?'Remove from Favorites':'Add to Favorites',run:()=>preference(topic,{favorite:!prefs[topic.key]?.favorite})},{label:'Add to Collection',run:()=>setModal({mode:'collection',topic})},{label:'Link Note',run:()=>setModal({mode:'note',topic})},{label:'Add Related Resource',run:()=>setModal({mode:'resource',topic})},...(topic.is_personal?[{label:'Edit Topic',run:()=>setModal({mode:'edit',topic})},{label:'Delete Topic',danger:true,run:()=>setModal({mode:'delete',topic})}]:[])]}
  async function submit(form){
    const {mode,topic}=modal
    if(mode==='collection'){await preference(topic,{collections:split(form.collections)},true);return}
    if(mode==='delete'){await deletePersonalTopic(user.id,topic.id);setData(d=>({...d,personal:d.personal.filter(t=>t.id!==topic.id).map(t=>({...t,related_topics:(t.related_topics||[]).filter(k=>k!==topic.key)})),links:d.links.filter(l=>l.topic_key!==topic.key&&!(l.entity_type==='topic'&&l.entity_id===topic.key)),preferences:d.preferences.filter(p=>p.topic_key!==topic.key)}));if(topicKey===topic.key)navigate('/topics');return}
    if(['new','edit'].includes(mode)){
      const name=form.name.trim();if(!name)throw new Error('Enter a topic name.')
      if(catalog.some(t=>t.key!==topic?.key&&[t.name,...t.aliases||[]].some(n=>normalizeTopic(n)===normalizeTopic(name))))throw new Error('This topic already exists. Open it to add your own links or save it to a collection.')
      if(form.image_url&&!safeNoteUrl(form.image_url))throw new Error('Use an http or https image URL.')
      const passages=form.scripture.split('\n').map(s=>s.trim()).filter(Boolean);if(passages.some(p=>!bibleUrl(p)))throw new Error('Use valid Scripture references, one per line.')
      const row=await saveTopic(user.id,{name,description:form.description.trim(),category:form.category,tags:split(form.tags),aliases:[...new Set([...split(form.aliases),...(mode==='edit'&&name!==topic.name?[topic.name]:[])])],image_url:form.image_url||null,related_topics:form.related_topics},mode==='edit'?topic.id:null)
      setData(d=>({...d,personal:[...d.personal.filter(t=>t.id!==row.id),row]}))
      try{for(const passage of passages){const link=await saveTopicLink(user.id,`personal:${row.id}`,'scripture',passage);setData(d=>({...d,links:[...d.links,link]}))}}catch{setError('Topic saved, but some Scripture links could not be saved. Add them from its Scripture tab.')}
      navigate(route(`personal:${row.id}`));return
    }
    if(form.entity_type==='resource'&&!safeNoteUrl(form.entity_id))throw new Error('Use a valid http or https resource URL.')
    if(form.entity_type==='scripture'&&!bibleUrl(form.entity_id))throw new Error('Enter a valid Bible passage.')
    const row=await saveTopicLink(user.id,topic.key,form.entity_type,form.entity_id.trim(),form.label.trim(),form.resource_kind)
    setData(d=>({...d,links:[...d.links.filter(l=>l.id!==row.id),row]}))
  }
  async function removeLink(id){try{await unlinkTopic(user.id,id);setData(d=>({...d,links:d.links.filter(l=>l.id!==id)}))}catch(e){setError(e.message)}}
  function clear(){setCategories([]);setSources([]);setTags([]);setRelated([]);setCollection('');setFavorites(false);setDateAdded('');setLocalQuery('');setQuery('');setDraftQuery('');setTab('All Topics');setLimit(24);setParams({})}
  const toggle=(values,set,value)=>{set(values.includes(value)?values.filter(v=>v!==value):[...values,value]);setLimit(24)}
  const allTags=[...new Set(catalog.flatMap(t=>t.tags||[]))].sort(),collections=[...new Set(data.preferences.flatMap(p=>p.collections||[]))].sort()
  const filtered=catalog.filter(t=>{
    const c=contents[t.key],p=prefs[t.key]||{}
    return (tab==='All Topics'||tab==='My Topics'&&t.is_personal||tab==='Trending'&&p.last_viewed&&Date.parse(p.last_viewed)>now-30*86400000||t.group===tab)&&(!categories.length||categories.includes(t.category))&&(!sources.length||sources.some(s=>c.sources.includes(s)))&&(!tags.length||tags.every(tag=>t.tags?.includes(tag)))&&(!related.length||related.every(k=>c[k].length))&&(!favorites||p.favorite)&&(!collection||p.collections?.includes(collection))&&(!dateAdded||Date.parse(t.created_at)>=Date.parse(dateAdded))&&matchesTopic(t,c,`${query} ${localQuery}`)
  }).sort((a,b)=>sort==='az'?a.name.localeCompare(b.name):sort==='viewed'?(Date.parse(prefs[b.key]?.last_viewed)||0)-(Date.parse(prefs[a.key]?.last_viewed)||0):sort==='updated'?(Date.parse(b.updated_at)||0)-(Date.parse(a.updated_at)||0):sort==='resources'?contents[b.key].resource.length-contents[a.key].resource.length:(prefs[b.key]?.view_count||0)-(prefs[a.key]?.view_count||0))
  const recent=catalog.filter(t=>prefs[t.key]?.last_viewed).sort((a,b)=>Date.parse(prefs[b.key].last_viewed)-Date.parse(prefs[a.key].last_viewed))
  const popular=[...catalog].sort((a,b)=>(prefs[b.key]?.view_count||0)-(prefs[a.key]?.view_count||0)||(a.priority??999)-(b.priority??999))
  const featured=catalog.find(t=>t.name==='Creation')||catalog[0]
  const count=(type,content)=>data.errors.includes({note:'notes',book:'books',doctrine_check:'checks',resource:'links',sermon:'sermons'}[type])?'—':content[type].length
  const filters=<><header><h2>Filters</h2><button onClick={clear}>Clear All</button></header><input aria-label="Filter topics" placeholder="Filter topics…" value={localQuery} onChange={e=>{setLocalQuery(e.target.value);setLimit(24)}}/>{[['Category',TOPIC_CATEGORIES,categories,setCategories],['Source',SOURCES,sources,setSources],['Tags',allTags,tags,setTags],['Related Content',TYPES.map(([v])=>v),related,setRelated]].map(([label,values,chosen,set])=><details key={label} open={['Category','Source'].includes(label)}><summary>{label}</summary>{values.map(value=><label className="topic-check" key={value}><input type="checkbox" checked={chosen.includes(value)} onChange={()=>toggle(chosen,set,value)}/>{label==='Related Content'?TYPES.find(([v])=>v===value)[1]:value}{label==='Category'&&` (${catalog.filter(t=>t.category===value).length})`}</label>)}</details>)}<details><summary>Collections & Favorites</summary><label className="topic-check"><input type="checkbox" checked={favorites} onChange={e=>setFavorites(e.target.checked)}/>Favorites</label><select aria-label="Collection" value={collection} onChange={e=>setCollection(e.target.value)}><option value="">All collections</option>{collections.map(c=><option key={c}>{c}</option>)}</select></details><details><summary>Date Added</summary><label>Added on or after<input type="date" value={dateAdded} onChange={e=>setDateAdded(e.target.value)}/></label></details></>
  const header=<><div className="topics-topbar"><form onSubmit={e=>{e.preventDefault();setQuery(draftQuery);setLimit(24);if(topicKey)navigate('/topics?q='+encodeURIComponent(draftQuery));else setParams(draftQuery?{q:draftQuery}:{})}}><Search size={20}/><input aria-label="Search topics" placeholder="Search topics (e.g., grace, election, prayer)…" value={draftQuery} onChange={e=>setDraftQuery(e.target.value)}/><button className="btn btn-primary">Search</button></form><AccountLink user={user}/><blockquote>“Study to show yourself approved to God…”<cite>2 Timothy 2:15</cite></blockquote></div><header className="topics-heading"><div><h1>{selected?selected.name:'Topics'}</h1><p>{selected?selected.description:'Explore key biblical and theological topics.'}</p></div><button className="btn btn-primary" disabled={loading||data.errors.includes('personal')} onClick={()=>setModal({mode:'new'})}>+ New Topic</button></header></>
  function card(t){const c=contents[t.key];return <article className="topic-card" key={t.key}><Link className="topic-card-open" to={route(t.key)}>{(safeNoteUrl(t.image_url)||t.image_url?.startsWith('/images/'))&&<img src={t.image_url} alt="" loading="lazy"/>}<h2>{t.name}{prefs[t.key]?.favorite&&<Star size={14} aria-label="Favorite"/>}</h2><p>{t.description}</p><div className="topic-counts"><span><FileText size={12}/>{count('resource',c)} resources</span><span>{count('note',c)} notes</span><span><Library size={12}/>{count('book',c)} books</span><span>{count('scripture',c)} passages</span><span>{count('doctrine_check',c)} checks</span><span>{count('sermon',c)} sermons</span></div><div className="topic-tags">{[t.category,...t.tags||[]].slice(0,4).map((tag,i)=><span key={`${tag}-${i}`}>{tag}</span>)}</div></Link><NoteMenu label={`Actions for ${t.name}`} actions={actions(t)}/></article>}
  return <div className="page topics-workspace">{header}{error&&<p role="alert" className="topic-error">{error}<button onClick={()=>setError('')}>Dismiss</button></p>}{data.errors.length>0&&<p role="status" className="topic-error">Some content could not load ({data.errors.join(', ')}). Counts may be incomplete. <button onClick={reload}>Retry</button></p>}
    {topicKey?(loading?<div className="topic-skeleton" role="status">Loading topic…</div>:selected?<TopicDetail key={selected.key} topic={selected} catalog={catalog} content={contents[selected.key]} links={data.links.filter(l=>l.topic_key===selected.key)} actions={actions(selected)} onLink={mode=>setModal({mode,topic:selected})} onUnlink={removeLink}/>:<section className="card"><h2>Topic unavailable</h2><p>This topic may have been deleted or may belong to another account.</p><Link to="/topics">Browse topics →</Link></section>):<>
    <nav className="topic-tabs" aria-label="Topic categories">{['All Topics','My Topics','Trending',...TOPIC_GROUPS].map(value=><button key={value} aria-pressed={tab===value} onClick={()=>{setTab(value);setLimit(24);if(value==='Trending')setSort('viewed')}}>{value}{value==='All Topics'?` (${catalog.length})`:value==='My Topics'?` (${data.personal.length})`:''}</button>)}</nav>
    <div className="topics-toolbar"><button className="topics-filter-button" onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={17}/>Filters</button><span>{filtered.length} topics</span><div className="topics-view"><button aria-pressed={view==='grid'} onClick={()=>setView('grid')}>Grid</button><button aria-pressed={view==='list'} onClick={()=>setView('list')}>List</button></div><select aria-label="Sort topics" value={sort} onChange={e=>setSort(e.target.value)}><option value="az">A–Z</option><option value="viewed">Recently Viewed</option><option value="updated">Recently Updated</option><option value="resources">Most Resources</option><option value="used">Most Used</option></select><Link to="/topics/index">Scripture / tag index →</Link></div>
    {tab==='Trending'&&<p className="card-meta">Topics you have visited in the last 30 days.</p>}
    <div className="topics-layout"><aside className="topic-filters">{filters}</aside><section className={`topic-results topic-${view}`} aria-label="Topic results">{loading?Array.from({length:6},(_,i)=><div className="topic-skeleton" key={i} role={i===0?'status':undefined}>{i===0?'Loading topics…':''}</div>):filtered.length?filtered.slice(0,limit).map(card):<div className="topic-empty"><h2>{tab==='My Topics'&&!data.personal.length?'Create your first topic.':tab==='Trending'?'Your recent topics will appear here.':'No topics match your search.'}</h2><p>Explore built-in topics, create your own, or remove a filter.</p><button onClick={clear}>Clear filters</button></div>}{filtered.length>limit&&<button className="btn btn-secondary topic-load-more" onClick={()=>setLimit(n=>n+24)}>Load more topics ({filtered.length-limit} remaining)</button>}</section>
    <aside className="topic-discovery">{featured&&<section className="card"><h2>Featured Topic</h2><Link className="topic-featured" to={route(featured.key)} style={{backgroundImage:`linear-gradient(#0f3d2e22,#0f3d2ed9),url(${featured.image_url})`}}><strong>{featured.name}</strong><span>{featured.description}</span><b>Explore Topic →</b></Link></section>}<section className="card"><h2>My Recently Viewed</h2>{recent.length?recent.slice(0,6).map(t=><Link key={t.key} to={route(t.key)}><BookOpen size={16}/><span>{t.name}<small>{relative(prefs[t.key]?.last_viewed)}</small></span></Link>):<p>Open a topic to start your history.</p>}<button onClick={()=>{setTab('Trending');setSort('viewed')}}>See all →</button></section><section className="card"><h2>{recent.length?'Popular in Your Study':'Suggested Starting Points'}</h2><small>{recent.length?'Ranked by your topic visits.':'Curated built-in topics to explore.'}</small>{popular.slice(0,5).map((t,i)=><Link key={t.key} to={route(t.key)}><span className="topic-rank">{i+1}</span>{t.name}</Link>)}</section></aside></div></>}
    <dialog ref={filterDialog} className="topic-dialog topic-filter-dialog" aria-label="Topic filters" onCancel={()=>setFilterOpen(false)}><button autoFocus onClick={()=>setFilterOpen(false)}>Done</button>{filterOpen&&filters}</dialog>
    {modal&&<TopicDialog key={`${modal.mode}-${modal.topic?.key}`} {...modal} catalog={catalog} data={data} preference={prefs[modal.topic?.key]} onClose={()=>setModal(null)} onSave={submit}/>}
  </div>
}

function TopicDetail({topic,catalog,content,links,actions,onLink,onUnlink}){
  const [tab,setTab]=useState('Overview')
  const related=catalog.filter(t=>t.key!==topic.key&&(content.topic.includes(t.key)||t.related_topics?.includes(topic.key)||t.tags?.some(tag=>topic.tags?.includes(tag))))
  const entityLink=(kind,row)=>kind==='sermon'?`/sermons/${row.id}`:kind==='book'?`/shelf/${row.id}`:kind==='note'?`/notebook/${row.id}`:`/checks/${row.id}`
  function remove(type,id){const link=links.find(l=>l.entity_type===type&&l.entity_id===id);return link?<button onClick={()=>onUnlink(link.id)} aria-label={`Unlink ${link.label||id}`}>Unlink</button>:null}
  return <section className="topic-detail"><header><Link to="/topics">← All Topics</Link><Link to={`/search?q=${encodeURIComponent(topic.name)}`}>Search all BSD content →</Link><NoteMenu label={`Actions for ${topic.name}`} actions={actions}/></header><nav className="topic-tabs" aria-label="Topic detail sections">{['Overview','Scripture','Library','Notes','Resources','Doctrine Check','Sermons'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
    {tab==='Overview'?<div className="topic-overview"><section className="card"><h2>About {topic.name}</h2><p>{topic.description||'Add a description to guide your study.'}</p><div className="topic-tags">{[topic.category,...topic.tags||[]].map(t=><span key={t}>{t}</span>)}</div><h3>Key Scripture</h3>{content.scripture.slice(0,6).map(ref=><Link key={ref} to={bibleUrl(ref)||`/search?q=${encodeURIComponent(ref)}`}>{ref} →</Link>)}{!content.scripture.length&&<p>No passages linked yet.</p>}<button onClick={()=>onLink('link')}>Add related content</button></section><section className="card"><h2>Related Topics</h2>{related.map(t=><Link key={t.key} to={route(t.key)}>{t.name} →</Link>)}{!related.length&&<p>No related topics yet. Add a link to connect this topic to another.</p>}<h3>Your connected content</h3>{TYPES.map(([key,label])=><p key={key}>{content[key].length} {label.toLowerCase()}</p>)}</section></div>:<section className="card topic-detail-content"><header><h2>{tab}</h2><button onClick={()=>onLink(tab==='Notes'?'note':tab==='Resources'?'resource':'link')}>+ Link content</button></header>
    {tab==='Scripture'&&(content.scripture.length?content.scripture.map(ref=><div className="topic-content-row" key={ref}><BookOpen size={18}/><Link to={bibleUrl(ref)||`/search?q=${encodeURIComponent(ref)}`}>{ref} · Open in Bible Study →</Link>{remove('scripture',ref)}</div>):<p>No Scripture linked yet.</p>)}
    {['Library','Notes','Doctrine Check','Sermons'].includes(tab)&&(()=>{const kind=tab==='Sermons'?'sermon':tab==='Library'?'book':tab==='Notes'?'note':'doctrine_check';const Icon=kind==='sermon'?Mic:kind==='book'?Library:kind==='note'?FileText:ShieldCheck;return <>{content[kind].map(row=><div className="topic-content-row" key={row.id}><Icon size={20}/><Link to={entityLink(kind,row)}><strong>{row.title||row.name||'Untitled'}</strong><small>{row.ref||row.author||row.authors||row.verdict}</small></Link>{remove(kind,row.id)}</div>)}{!content[kind].length&&<p>No {tab.toLowerCase()} connected yet. Link existing content or tag it with “{topic.name}”.</p>}</>})()}
    {tab==='Notes'&&<Link className="btn btn-primary" to="/notebook/new" state={{title:`${topic.name} study notes`,tags:[topic.name],topic_key:topic.key}}>Create linked note →</Link>}
    {tab==='Doctrine Check'&&<Link className="btn btn-primary" to="/checks" state={{topicContext:{key:topic.key,name:topic.name}}}>Run a check for this topic →</Link>}
    {tab==='Resources'&&(content.resource.length?content.resource.map(r=><div className="topic-content-row" key={r.id}><FileText size={18}/><a href={safeNoteUrl(r.entity_id)||undefined} target="_blank" rel="noreferrer"><strong>{r.label||r.entity_id}</strong><small>{r.resource_kind} ↗</small></a>{remove('resource',r.entity_id)}</div>):<p>No resources saved yet. Add an article, video, website, or study tool.</p>)}
    </section>}
  </section>
}
