import Highlight from '@tiptap/extension-highlight'
import NoteScan from './NoteScan'
import { useEditor, useEditorState, EditorContent } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import Image from '@tiptap/extension-image'
import { Node } from '@tiptap/core'
import { useRef, useState } from 'react'
import { uploadEntryPhoto } from '../lib/entryPhotos'
import { plainDocument, safeNoteUrl } from '../lib/noteModel'
import { Bold, Italic, Underline, List, ListOrdered, Quote, BookOpen, Link as LinkIcon, Image as ImageIcon, Undo2, Redo2 } from 'lucide-react'
const ScriptureQuote=Node.create({name:'scriptureQuote',group:'block',content:'block+',defining:true,
  addAttributes:()=>({reference:{default:'',parseHTML:element=>element.getAttribute('data-reference')||''}}),
  parseHTML:()=>[{tag:'blockquote[data-scripture]',contentElement:element=>element.querySelector('.scripture-content')||element}],
  renderHTML:({node})=>['blockquote',{'data-scripture':'true','data-reference':node.attrs.reference,class:'notes-scripture'},['div',{class:'scripture-content'},0],['cite',{contenteditable:'false'},node.attrs.reference||'Scripture quotation']]
})
export default function NoteRichEditor({note,onChange,userId,books}) {
  const upload=useRef(null), [error,setError]=useState(''),[tool,setTool]=useState(null),[value,setValue]=useState('')
  const editor=useEditor({extensions:[StarterKit.configure({heading:{levels:[2,3]},link:{openOnClick:false}}),Image,ScriptureQuote,Highlight.configure({multicolor:true})],content:note.rich_doc || plainDocument(note.body),editorProps:{attributes:{'aria-label':'Note content',role:'textbox','aria-multiline':'true'}},onUpdate:({editor})=>onChange({rich_doc:editor.getJSON(),body:editor.getText()})})
  const active=useEditorState({editor,selector:({editor:e})=>e?{style:e.isActive('heading',{level:2})?'2':e.isActive('heading',{level:3})?'3':'paragraph',...Object.fromEntries(['bold','italic','underline','bulletList','orderedList','blockquote','scriptureQuote','link'].map(k=>[k,e.isActive(k)])),undo:e.can().undo(),redo:e.can().redo()}:null})
  if(!editor)return <p>Loading editor…</p>
  const icons={Bold,Italic,Underline,Bullets:List,'Numbered list':ListOrdered,Quote,Scripture:BookOpen,Link:LinkIcon,Image:ImageIcon,Undo:Undo2,Redo:Redo2}
  const keys={Bold:'bold',Italic:'italic',Underline:'underline',Bullets:'bulletList','Numbered list':'orderedList',Quote:'blockquote',Scripture:'scriptureQuote',Link:'link'}
  const action=(label,command)=> {const Icon=icons[label];return <button type="button" key={label} title={label} aria-label={label} aria-pressed={keys[label]?!!active?.[keys[label]]:undefined} disabled={label==='Undo'?!active?.undo:label==='Redo'?!active?.redo:false} onClick={command}><Icon size={17}/></button>}
  return <><div className="notes-toolbar" role="group" aria-label="Formatting">
    <select aria-label="Paragraph style" value={active?.style||'paragraph'} onChange={e=>e.target.value==='paragraph'?editor.chain().focus().setParagraph().run():editor.chain().focus().setHeading({level:Number(e.target.value)}).run()}><option value="paragraph">Paragraph</option><option value="2">Heading</option><option value="3">Subheading</option></select>
    {action('Bold',()=>editor.chain().focus().toggleBold().run())}{action('Italic',()=>editor.chain().focus().toggleItalic().run())}{action('Underline',()=>editor.chain().focus().toggleUnderline().run())}{action('Bullets',()=>editor.chain().focus().toggleBulletList().run())}{action('Numbered list',()=>editor.chain().focus().toggleOrderedList().run())}{action('Quote',()=>editor.chain().focus().toggleBlockquote().run())}{action('Scripture',()=>{setTool('scripture');setValue(editor.getAttributes('scriptureQuote').reference||note.ref||'')})}
    {active?.scriptureQuote&&<button title="Remove Scripture callout" aria-label="Remove Scripture callout" onClick={()=>editor.chain().focus().lift('scriptureQuote').run()}>×</button>}
    {action('Link',()=>{setTool('link');setValue(editor.getAttributes('link').href||'')})}
    <span className="note-highlight" role="group" aria-label="Highlight text">{[['Yellow','#f5e7a3'],['Green','#cde6d2'],['Blue','#cee3f3'],['Pink','#efd2df']].map(([name,color])=><button key={color} type="button" title={`Highlight ${name.toLowerCase()}`} aria-label={`Highlight ${name.toLowerCase()}`} style={{background:color}} onMouseDown={event=>event.preventDefault()} onClick={()=>editor.chain().focus().setHighlight({color}).run()}>{name.slice(0,1)}</button>)}<button type="button" title="Remove highlight" aria-label="Remove highlight" onMouseDown={event=>event.preventDefault()} onClick={()=>editor.chain().focus().unsetHighlight().run()}>×</button></span><NoteScan editor={editor} userId={userId} note={note} onChange={onChange} books={books}/>{action('Image',()=>upload.current.click())}{action('Undo',()=>editor.chain().focus().undo().run())}{action('Redo',()=>editor.chain().focus().redo().run())}
    <input ref={upload} hidden type="file" accept="image/*" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setError('Uploading image…');try{const src=await uploadEntryPhoto(userId,file);if(!editor.isDestroyed)editor.chain().focus().setImage({src,alt:file.name}).run();setError('')}catch(err){setError(err.message)}finally{e.target.value=''}}}/>
  </div>{tool&&<form className="notes-inline-tool" onSubmit={e=>{e.preventDefault();if(tool==='scripture'){if(editor.isActive('scriptureQuote'))editor.chain().focus().updateAttributes('scriptureQuote',{reference:value}).run();else editor.chain().focus().wrapIn('scriptureQuote',{reference:value}).run()}else{if(!value)editor.chain().focus().unsetLink().run();else if(safeNoteUrl(value)||(value.startsWith('/')&&!value.startsWith('//')))editor.chain().focus().setLink({href:value}).run();else{setError('Use a valid web address or BSD path.');return}}setTool(null);setError('')}} onKeyDown={e=>{if(e.key==='Escape'){setTool(null);editor.commands.focus()}}}><label>{tool==='scripture'?'Quotation reference and translation':'Web address or BSD link'}<input autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder={tool==='scripture'?'John 1:1 · BSB':'https://… or /notebook/…'}/></label><button type="submit">Apply</button><button type="button" onClick={()=>{setTool(null);editor.commands.focus()}}>Cancel</button></form>}{error&&<p role="status">{error}</p>}<EditorContent editor={editor}/></>
}
