import {useEffect,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import ScriptureText from './ScriptureText'
import {getSermon} from '../lib/sermons'
import {useAuth} from '../App'
import {sermonTitle,timestamp,sermonBibleUrl} from '../lib/sermonModel'
import '../screens/Sermons.css'
export function SermonRefs({sermon}){return <div className="sermon-refs">{sermon.primary_ref&&<div><strong>Primary Text: {sermon.primary_text}</strong><Link to={sermonBibleUrl(sermon.primary_ref,sermon.id)}>Read primary text in Bible Study →</Link></div>}{sermon.detected_refs?.length?sermon.detected_refs.map(r=><div key={r.raw}><ScriptureText text={r.raw} sermonId={sermon.id}/><Link to={sermonBibleUrl(r,sermon.id)}>Open in Bible Study →</Link><Link to="/notebook/new" state={{sermon_id:sermon.id,title:`${sermonTitle(sermon)} — ${r.raw}`,ref:r.raw,tags:sermon.tags,note_type:'resource'}}>Add to Notes</Link></div>):<p>No references detected yet. Add or edit the transcript to include explicit book/chapter references.</p>}</div>}
export function SermonTranscript({sermon}){const [query,setQuery]=useState('');const cues=sermon.transcript_cues||[];const sections=cues.length?cues:sermon.transcript_text?.split(/\n\s*\n/).map(text=>({text}))||[];const filtered=sections.filter(c=>c.text.toLowerCase().includes(query.toLowerCase()));return <><p className="sermon-link-help">Underlined Scripture references are clickable. Select one to preview the passage and open it in Bible Study.</p><input className="input" type="search" aria-label="Search transcript" placeholder="Search transcript…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="sermon-transcript">{filtered.map((c,i)=><section key={i}>{c.start!=null&&<time>{timestamp(c.start)}</time>}<ScriptureText text={c.text} sermonId={sermon.id}/></section>)}{!sections.length&&<p>No transcript yet. Paste text or upload a transcript from Edit.</p>}{sections.length>0&&!filtered.length&&<p>No matching transcript sections.</p>}</div></>}
export function GuideBody({guide,sermonId}){return <div className="sermon-guide"><p>{guide.summary}</p>{[['outline','Outline'],['key_points','Key Points'],['discussion_questions','Discussion Questions'],['application','Application']].map(([key,label])=><section key={key}><h3>{label}</h3><ol>{(guide[key]||[]).map((t,i)=><li key={i}><ScriptureText text={t} sermonId={sermonId}/></li>)}</ol></section>)}<h3>Cross-References</h3>{(guide.cross_refs||[]).map((r,i)=><div key={i}><ScriptureText text={r.ref} sermonId={sermonId}/><p>{r.note}</p></div>)}</div>}
export default function SermonBiblePanel(){const user=useAuth(),[params,setParams]=useSearchParams(),id=params.get('sermon');const [state,setState]=useState({row:null,error:'',loading:true}),[tab,setTab]=useState('Transcript');useEffect(()=>{let active=true;if(id)getSermon(user.id,id).then(row=>{if(active)setState({row,error:'',loading:false})}).catch(e=>{if(active)setState({row:null,error:e.message,loading:false})});return()=>{active=false}},[id,user.id]);if(!id)return null;return <aside className="card sermon-bible-panel"><header><h2>Sermon study</h2><button aria-label="Close sermon panel" onClick={()=>{const next=new URLSearchParams(params);next.delete('sermon');setParams(next)}}>×</button></header>{state.loading?<p>Loading sermon…</p>:state.error?<p role="alert">Could not load this sermon. <Link to="/sermons">Open Sermons</Link></p>:<><Link to={`/sermons/${id}`}><h3>{sermonTitle(state.row)}</h3></Link><p className="sermon-link-help">Click an underlined Bible reference for a BSB preview, then choose <strong>Open in Bible Study</strong> to change the passage. Your sermon stays here.</p><div className="sermon-tabs">{['Transcript','Scripture','Study Guide'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Transcript'?<SermonTranscript key={state.row.id} sermon={state.row}/>:tab==='Scripture'?<SermonRefs sermon={state.row}/>:state.row.study_guide?<GuideBody guide={state.row.study_guide} sermonId={id}/>:<p>Generate a study guide from the sermon page.</p>}<Link className="btn btn-secondary" to="/notebook/new" state={{sermon_id:id,title:`Notes: ${sermonTitle(state.row)}`,tags:state.row.tags,note_type:'resource'}}>Create linked note</Link></>}</aside>}
