import { useEffect, useRef, useState } from 'react'
import { TOPIC_CATEGORIES } from '../lib/topicCatalog'
export default function TopicDialog({mode,topic,catalog,data,preference,onClose,onSave}){
  const dialog=useRef(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [form,setForm]=useState({name:mode==='edit'?topic.name:'',description:mode==='edit'?topic.description:'',category:mode==='edit'?topic.category:'Other',tags:mode==='edit'?topic.tags.join(', '):'',aliases:mode==='edit'?(topic.aliases||[]).join(', '):'',image_url:mode==='edit'?topic.image_url||'':'',related_topics:mode==='edit'?topic.related_topics||[]:[],scripture:'',entity_type:mode==='note'?'note':mode==='resource'?'resource':'scripture',entity_id:'',label:'',resource_kind:'website',collections:(preference?.collections||[]).join(', ')})
  const change=(key,value)=>setForm(f=>({...f,[key]:value}))
  useEffect(()=>{dialog.current.showModal()},[])
  const title=mode==='new'?'New Topic':mode==='edit'?'Edit Topic':mode==='delete'?'Delete Topic?':mode==='collection'?'Topic Collections':'Add Related Content'
  return <dialog ref={dialog} className="topic-dialog" aria-labelledby="topic-dialog-title" onCancel={e=>{if(busy)e.preventDefault();else onClose()}}><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await onSave(form);onClose()}catch(err){setError(err.message)}finally{setBusy(false)}}}><header><h2 id="topic-dialog-title">{title}</h2><button type="button" disabled={busy} onClick={onClose} aria-label="Close topic dialog">×</button></header>
    {mode==='delete'?<p>Delete “{topic.name}”? Your notes, books, and assessments will remain. This cannot be undone.</p>:mode==='collection'?<label>Collections<input autoFocus value={form.collections} onChange={e=>change('collections',e.target.value)} placeholder="Separate names with commas" list="topic-collection-names"/><datalist id="topic-collection-names">{[...new Set(data.preferences.flatMap(p=>p.collections||[]))].map(c=><option key={c} value={c}/>)}</datalist></label>:['new','edit'].includes(mode)?<>
    <label>Topic Name<input required autoFocus maxLength={120} value={form.name} onChange={e=>change('name',e.target.value)}/></label><label>Description<textarea rows={3} value={form.description} onChange={e=>change('description',e.target.value)}/></label>
    <label>Category<select value={form.category} onChange={e=>change('category',e.target.value)}>{TOPIC_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label>
    <label>Tags<input value={form.tags} onChange={e=>change('tags',e.target.value)} placeholder="Separate tags with commas"/></label><label>Aliases / synonyms<input value={form.aliases} onChange={e=>change('aliases',e.target.value)} placeholder="Separate aliases with commas"/></label>
    <label>Optional image URL<input type="url" value={form.image_url} onChange={e=>change('image_url',e.target.value)} placeholder="https://…"/></label>
    <label>Related topics<select multiple value={form.related_topics} onChange={e=>change('related_topics',[...e.target.selectedOptions].map(o=>o.value))}>{catalog.filter(t=>t.key!==topic?.key).map(t=><option key={t.key} value={t.key}>{t.name}</option>)}</select><small>Choose any overlapping topics; no strict hierarchy is required.</small></label>
    {mode==='new'&&<label>Related Scripture<textarea rows={2} value={form.scripture} onChange={e=>change('scripture',e.target.value)} placeholder="One passage per line, e.g. John 3:16"/></label>}
    </>:<>
    <label>Content type<select value={form.entity_type} onChange={e=>{change('entity_type',e.target.value);change('entity_id','')}}>{[['scripture','Scripture'],['book','Library Book'],['note','Note'],['resource','Resource'],['doctrine_check','Doctrine Check'],['topic','Related Topic'],['sermon','Sermon']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
    {['book','note','doctrine_check','topic','sermon'].includes(form.entity_type)?<label>Choose content<select required value={form.entity_id} onChange={e=>change('entity_id',e.target.value)}><option value="">Select…</option>{(form.entity_type==='sermon'?data.sermons:form.entity_type==='book'?data.books:form.entity_type==='note'?data.notes:form.entity_type==='doctrine_check'?data.checks:catalog.filter(t=>t.key!==topic.key)).map(row=><option key={row.id||row.key} value={form.entity_type==='topic'?row.key:row.id}>{row.title||row.name||'Untitled'}</option>)}</select></label>:<label>{form.entity_type==='scripture'?'Scripture reference':'Resource URL'}<input required type={form.entity_type==='resource'?'url':'text'} value={form.entity_id} onChange={e=>change('entity_id',e.target.value)} placeholder={form.entity_type==='scripture'?'Romans 8:28-30':'https://…'}/></label>}
    {form.entity_type==='resource'&&<><label>Resource title<input required value={form.label} onChange={e=>change('label',e.target.value)}/></label><label>Resource type<select value={form.resource_kind} onChange={e=>change('resource_kind',e.target.value)}>{['article','video','website','tool'].map(k=><option key={k}>{k}</option>)}</select></label></>}
    </>}
    {error&&<p role="alert">{error}</p>}<footer><button type="button" autoFocus={mode==='delete'} disabled={busy} onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?'Saving…':mode==='delete'?'Delete Topic':'Save'}</button></footer>
  </form></dialog>
}
